PLUGIN_NAME=		metrics_exporter
PLUGIN_VERSION=		1.4.1
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		Prometheus exporter for OPNsense metrics
PLUGIN_DEPENDS=		os-node_exporter${PLUGIN_PKGSUFFIX}
PLUGIN_MAINTAINER=	brendan.bank@gmail.com
PLUGIN_WWW=		https://brendanbank.github.io/banzai-plugins/releases/26.1/metrics_exporter.html

.include "../../Mk/plugins.mk"
