PLUGIN_NAME=		metrics_exporter
PLUGIN_VERSION=		1.4
PLUGIN_COMMENT=		Prometheus exporter for OPNsense metrics
PLUGIN_DEPENDS=		os-node_exporter${PLUGIN_PKGSUFFIX}
PLUGIN_MAINTAINER=	brendan.bank@gmail.com
PLUGIN_WWW=		https://github.com/brendanbank/banzai-plugins

.include "../../Mk/plugins.mk"
