[status]
command:/usr/local/opnsense/scripts/kea_ddns/ddns_status.py
parameters:
type:script_output
message:get kea-ddns daemon status

[ddns_leases4]
command:/usr/local/opnsense/scripts/kea_ddns/ddns_leases.py
parameters:--proto inet
type:script_output
message:get kea ddns leases (DHCPv4)

[ddns_leases6]
command:/usr/local/opnsense/scripts/kea_ddns/ddns_leases.py
parameters:--proto inet6
type:script_output
message:get kea ddns leases (DHCPv6)
