[status]
command:/usr/local/opnsense/scripts/kea_ddns/ddns_status.py
parameters:
type:script_output
message:get kea-ddns daemon status

[resend_ddns4]
command:/usr/local/opnsense/scripts/kea_ddns/ddns_resend.py
parameters:--proto inet --address %s
type:script_output
message:resend DDNS for DHCPv4 lease

[resend_ddns6]
command:/usr/local/opnsense/scripts/kea_ddns/ddns_resend.py
parameters:--proto inet6 --address %s
type:script_output
message:resend DDNS for DHCPv6 lease

[ddns_leases4]
command:/usr/local/opnsense/scripts/kea_ddns/ddns_leases.py
parameters:--proto inet
type:script_output
message:get kea ddns leases (DHCPv4)

[ddns_leases6]
command:/usr/local/opnsense/scripts/kea_ddns/ddns_leases.py
parameters:--proto inet6
type:script_output
message:get kea ddns leases (DHCPv6)
