[status]
command:/usr/local/opnsense/scripts/kea_ddns/ddns_status.py
parameters:
type:script_output
message:get kea-ddns daemon status

[ddns_leases]
command:/usr/local/opnsense/scripts/kea_ddns/ddns_leases.py
parameters:
type:script_output
message:get kea ddns leases
