PLUGIN_NAME=		hello_world
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Hello World example plugin
PLUGIN_MAINTAINER=	brendan.bank@gmail.com
PLUGIN_WWW=		https://github.com/brendanbank/banzai-plugins

.include "../../Mk/plugins.mk"
