PLUGIN_NAME=		hello_world
PLUGIN_VERSION=		1.1
PLUGIN_COMMENT=		Hello World example plugin
PLUGIN_MAINTAINER=	brendan.bank@gmail.com
PLUGIN_WWW=		https://brendanbank.github.io/banzai-plugins/releases/26.1/hello_world.html

.include "../../Mk/plugins.mk"
