PLUGIN_NAME=		kea-ddns
PLUGIN_VERSION=		2.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Kea DHCP Dynamic DNS (DDNS) support
PLUGIN_MAINTAINER=	brendan.bank@gmail.com
PLUGIN_WWW=		https://brendanbank.github.io/banzai-plugins/releases/26.1/kea_ddns.html

.include "../../Mk/plugins.mk"
