PLUGIN_NAME=		kea-ddns
PLUGIN_VERSION=		2.7
PLUGIN_COMMENT=		Kea DHCP Dynamic DNS (DDNS) support
PLUGIN_MAINTAINER=	brendan.bank@gmail.com
PLUGIN_WWW=		https://brendanbank.github.io/banzai-plugins/releases/${PLUGIN_ABI}/kea_ddns.html

.include "../../Mk/plugins.mk"
